---

- name: create the docker directory
  file:
    path: "{{ docker_dir }}"
    owner: root
    group: root
    mode: "0711"
    state: directory

- name: relink the docker directory if needed
  file:
    src: "{{ docker_dir }}"
    dest: /var/lib/docker
    state: link
    force: "{{ docker_force_dir | bool }}"
  when: docker_dir != '/var/lib/docker'
