---

- import_tasks: config.yml

- include_tasks: "pkg_config_{{ ansible_facts['distribution'] }}.yml"

- import_tasks: pkg.yml

- import_tasks: service.yml

- meta: flush_handlers

- import_tasks: fw.yml
