---

- name: get package facts
  package_facts:
    manager: "auto"

- name: get the current docker-ce version
  set_fact:
    __docker_current_pkg_result: "{{ ansible_facts['packages']['docker-ce'][0]['version'] }}"
  when: ansible_facts['packages']['docker-ce'] is defined

- include_role:
    name: t18s.fr_pkg
  vars:
    pkg_list:
      - docker-ce
  when: docker_version is not defined

- include_role:
    name: t18s.fr_pkg
  vars:
    pkg_list:
      - name: docker-ce
        version: "{{ docker_version }}"
  when: docker_version is defined

- name: get the new docker-ce version
  set_fact:
    __docker_new_pkg_result: "{{ ansible_facts['packages']['docker-ce'][0]['version'] }}"
  when: ansible_facts['packages']['docker-ce'] is defined

- name: trigger docker containers restart
  debug:
    msg: "docker-ce: {{ __docker_current_pkg_result }} -> {{ __docker_new_pkg_result }}"
  changed_when: True
  when: __docker_current_pkg_result != __docker_new_pkg_result
  notify:
    - docker restart
